### ISSUE TITLE
Walletd

### ISSUE THREAD

**Issue by Cideg** [worktips/worktipscoin#4]
Hi, I have the problem that the wallet does not recognize an address. 

WARNING Can't validate address WtiptjGr6oRdZVFqurkGmc1DXreHk7sSsdfdsafdafdsfasdf+hfdjdjgjgdjggdjfdjgdghasg502a46130f6823
2018-Sep-09 18:20:05.690195 WARNING Error while sending transaction: Bad address

How could the bug be fixed?

Many thx

**Comment by Vordas** [comment]
How was that address created? It doesn't really look valid.

**Comment by Vordas** [comment]
Middle part of the address looks like it was typed out at random so it is not a valid address. Closing the issue. If you want, you can re-open.
